# Generated by Django 5.0.6 on 2025-11-17 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('faculty_id', models.CharField(blank=True, max_length=50)),
                ('consent_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('granted', models.BooleanField()),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
