# Generated by Django 5.0.6 on 2023-10-01 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('dashboard_widgets', models.JSONField(blank=True, default=dict)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal Only'), ('private', 'Private')], default='internal', max_length=20)),
                ('show_email', models.BooleanField(default=True)),
                ('show_office_hours', models.BooleanField(default=True)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('office', 'Office Hours')], default='email', max_length=20)),
                ('calendar_view', models.CharField(choices=[('month', 'Month'), ('week', 'Week'), ('day', 'Day')], default='week', max_length=20)),
                ('working_hours_start', models.TimeField(default='09:00:00')),
                ('working_hours_end', models.TimeField(default='17:00:00')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.faculty')),
            ],
        ),
    ]