# Generated by Django 5.2.8 on 2025-11-21 14:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('users', '0002_alter_user_failed_login_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthicsApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('principal_investigator', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('submission_date', models.DateField(default=django.utils.timezone.now)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='submitted', max_length=50)),
                ('protocol_number', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(default='minimal', max_length=50)),
                ('project_description', models.TextField(blank=True)),
                ('consent_process', models.TextField(blank=True)),
                ('data_management', models.TextField(blank=True)),
                ('documents', models.JSONField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethics_applications', to='users.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('funding_agency', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('submission_date', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('status', models.CharField(default='draft', max_length=50)),
                ('documents', models.JSONField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='users.faculty')),
            ],
        ),
    ]
