# Generated by Django 5.2.8 on 2025-11-21 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_ethicsapplication_grant'),
        ('users', '0002_alter_user_failed_login_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_id', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('file_size', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('available', 'Available'), ('failed', 'Failed'), ('scheduled', 'Scheduled')], default='processing', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('students', 'Students Only'), ('private', 'Private')], default='private', max_length=20)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='users.faculty')),
            ],
        ),
    ]