@echo off
echo Generating WBS...
call .\node_modules\.bin\mmdc.cmd -i wbs.mmd -o wbs.png
echo Generating Gantt...
call .\node_modules\.bin\mmdc.cmd -i gantt.mmd -o gantt.png
echo Generating Network...
call .\node_modules\.bin\mmdc.cmd -i network.mmd -o network.png
echo Generating Context DFD...
call .\node_modules\.bin\mmdc.cmd -i context_dfd.mmd -o context_dfd.png
echo Generating Class Diagram...
call .\node_modules\.bin\mmdc.cmd -i class_diagram.mmd -o class_diagram.png
echo Generating Activity Diagram...
call .\node_modules\.bin\mmdc.cmd -i activity.mmd -o activity.png
echo Generating ROI Chart...
python generate_roi.py
echo Done.
