# Generated by Django 5.0.6 on 2025-11-17 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('credits', models.IntegerField()),
                ('instructor_id', models.CharField(max_length=50)),
                ('schedule', models.JSONField(blank=True, null=True)),
                ('students', models.JSONField(blank=True, null=True)),
                ('assignments', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.CharField(max_length=100)),
                ('prerequisites', models.JSONField(blank=True, null=True)),
                ('syllabus', models.CharField(blank=True, max_length=200)),
                ('textbooks', models.JSONField(blank=True, null=True)),
                ('enrollment_limit', models.IntegerField()),
                ('waitlist', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grading_scale', models.JSONField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, null=True)),
                ('materials', models.JSONField(blank=True, null=True)),
                ('announcements', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50)),
                ('course_id', models.CharField(max_length=50)),
                ('enrollment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='active', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
