# Generated by Django 5.0.6 on 2025-12-05 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('section_number', models.IntegerField()),
                ('instructor_id', models.CharField(blank=True, max_length=50)),
                ('schedule', models.JSONField(blank=True, null=True)),
                ('students', models.JSONField(blank=True, null=True)),
                ('enrollment_limit', models.IntegerField()),
                ('waitlist', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]