# Generated by Django 5.0.6 on 2025-12-05 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_section_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_corequisite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_for', to='courses.course')),
                ('prerequisite_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Prerequisite',
                'verbose_name_plural': 'Course Prerequisites',
                'unique_together': {('course', 'prerequisite_course')},
            },
        ),
    ]