# Generated by Django 5.0.6 on 2025-11-17 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('points', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('submissions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField()),
                ('allow_late_submission', models.BooleanField()),
                ('late_penalty', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_submissions', models.IntegerField()),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('rubric', models.JSONField(blank=True, null=True)),
                ('visible_to_students', models.BooleanField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50)),
                ('course_id', models.CharField(max_length=50)),
                ('assignment_id', models.CharField(blank=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('letter_grade', models.CharField(blank=True, max_length=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('grader_id', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('assignment_id', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('late_submission', models.BooleanField()),
                ('revision_history', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
