# Generated by Django 5.2.8 on 2025-12-04 22:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseprerequisite'),
        ('student', '0001_initial'),
        ('users', '0003_remove_student_academic_records_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollmentHistory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('drop_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='enrolled', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('enrollment_type', models.CharField(default='regular', max_length=20)),
                ('waitlist_position', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='courses.course')),
                ('enrollment_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student.enrollmentperiod')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='courses.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_history', to='users.student')),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'course', 'section', 'enrollment_period')},
            },
        ),
    ]
