# Generated by Django 5.2.8 on 2025-12-04 22:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseprerequisite'),
        ('student', '0002_studentenrollmenthistory'),
        ('users', '0003_remove_student_academic_records_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCourseAssignment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('assignment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(default='instructor', max_length=50)),
                ('is_primary', models.BooleanField(default=True)),
                ('workload_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='courses.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='users.faculty')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='courses.section')),
            ],
            options={
                'ordering': ['-assignment_date'],
                'unique_together': {('faculty', 'course', 'section', 'start_date')},
            },
        ),
    ]
