# Generated by Django 5.2.8 on 2025-12-07 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseprerequisite'),
        ('student', '0004_enrollmentauditlog_facultyapprovalrequest'),
        ('users', '0003_remove_student_academic_records_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollmentCart',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_carts', to='users.student')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
