# Generated by Django 5.2.8 on 2025-12-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentenrollmentcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentperiod',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='enrollmentperiod',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
