# Generated by Django 5.2.8 on 2025-12-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_failed_login_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_records',
        ),
        migrations.RemoveField(
            model_name='student',
            name='housing_application',
        ),
        migrations.RemoveField(
            model_name='student',
            name='library_books',
        ),
        migrations.RemoveField(
            model_name='student',
            name='meal_plan',
        ),
    ]
